"""Named study extents the models are run over.

An area of interest is held in WGS84, because that is how extents get quoted and
compared between people, and converted to whatever CRS the caller works in on
demand. Keeping the definition in one place means an extent is never re-typed
from a map into a script.
"""

from dataclasses import dataclass

import geopandas as gpd
from shapely.geometry import Polygon, box

from landloss.domain import constants
from landloss.io import ASSETS_DIR

WGS84 = "EPSG:4326"


@dataclass(frozen=True)
class AreaOfInterest:
    """A named rectangular study extent, defined in WGS84.

    Attributes:
        name: A human readable name, used in outputs and file names.
        west: Western boundary, as a WGS84 longitude.
        south: Southern boundary, as a WGS84 latitude.
        east: Eastern boundary, as a WGS84 longitude.
        north: Northern boundary, as a WGS84 latitude.
    """

    name: str
    west: float
    south: float
    east: float
    north: float

    def bbox(
        self, crs: int | str = constants.DEFAULT_CRS
    ) -> tuple[float, float, float, float]:
        """Return the extent as (minx, miny, maxx, maxy) in the given CRS.

        Args:
            crs: The coordinate reference system to express the extent in.

        Returns:
            The bounding box, ready to pass to a reader.
        """
        bounds = self.to_geoseries(crs).total_bounds
        minx, miny, maxx, maxy = (float(value) for value in bounds)
        return (minx, miny, maxx, maxy)

    def polygon(self, crs: int | str = constants.DEFAULT_CRS) -> Polygon:
        """Return the extent as a polygon in the given CRS."""
        return self.to_geoseries(crs).iloc[0]

    def to_geoseries(self, crs: int | str = constants.DEFAULT_CRS) -> gpd.GeoSeries:
        """Return the extent as a single-element GeoSeries in the given CRS."""
        return gpd.GeoSeries(
            [box(self.west, self.south, self.east, self.north)], crs=WGS84
        ).to_crs(crs)


# A small pilot area in Wellington, used to exercise the workflow end to end
# before it is run over the full study area.
SMALL_WLG_PILOT = AreaOfInterest(
    name="Small Wellington pilot",
    west=174.772318,
    south=-41.32486560367306,
    east=174.80616774743507,
    north=-41.309796,
)

# A pilot box over Johnsonville, Newlands and Paparangi, for the slope failure
# susceptibility work. SMALL_WLG_PILOT cannot be used for that: it sits over Mt
# Victoria and Hataitai, and holds not one polygon of the Wellington City
# earthworks record the slope modification factor is built from. This box is
# where that record is densest -- about 190 of the 453 cut and fill polygons,
# roughly 2.8 km2 of mapped earthworks in 16 km2 of hill suburb.
WLG_EARTHWORKS_PILOT = AreaOfInterest(
    name="Johnsonville and Newlands",
    west=174.78881496861425,
    south=-41.231493541571886,
    east=174.83750131663035,
    north=-41.194728870313334,
)

# A pilot box over the lower Hutt Valley, from the Petone and Seaview foreshore
# up the Hutt River to Melling, for the lateral spreading work. SMALL_WLG_PILOT
# holds almost no waterways; this box holds the study's largest river, the
# Waiwhetu Stream, the harbour edge and the reclaimed ground at Seaview, which
# is where a free-face buffer has something to do.
LOWER_HUTT_PILOT = AreaOfInterest(
    name="Lower Hutt Valley",
    west=174.86,
    south=-41.245,
    east=174.935,
    north=-41.195,
)

# The Canterbury earthquake sequence study area, covering Christchurch city and
# the flat land around it. This is the extent the observed land damage evidence
# is drawn from -- the only New Zealand dataset holding both settled land claims
# and mapped land damage -- rather than an area the Wellington model is run over.
#
# The flat versus sloping split inside it is not a rectangle and cannot be held
# here; see CHCH_FLAT_ONLY and CHCH_SLOPE_ONLY in
# landloss.exposure.land.landform.
CHRISTCHURCH = AreaOfInterest(
    name="Christchurch",
    west=172.22727348821033,
    south=-43.669039807974436,
    east=172.92244713169507,
    north=-43.28668860936209,
)

# The packaged study area boundaries, generated by
# landloss.io.one_offs.gen_study_extent.
STUDY_AREAS_PATH = ASSETS_DIR / "study-areas.geoparquet"


def get_study_areas(crs: int | str = constants.DEFAULT_CRS) -> gpd.GeoDataFrame:
    """Load the four territorial authorities making up the study area.

    Each authority is a separate row, so results can be reported per territorial
    authority rather than only for the study area as a whole. The boundaries are
    packaged with the library, so this reads from disk and needs no API key; run
    ``gen_study_extent.py`` to regenerate them.

    Args:
        crs: The coordinate reference system to return the boundaries in.

    Returns:
        A GeoDataFrame with one row per territorial authority, carrying
        ``ta_code``, ``name`` and ``land_area_sq_km``.

    Raises:
        FileNotFoundError: If the packaged asset is missing.
    """
    if not STUDY_AREAS_PATH.exists():
        msg = (
            f"Study area boundaries are missing from {STUDY_AREAS_PATH}. "
            "Regenerate them with landloss/io/one_offs/gen_study_extent.py."
        )
        raise FileNotFoundError(msg)

    return gpd.read_parquet(STUDY_AREAS_PATH).to_crs(crs)


def get_study_area(
    name: str, crs: int | str = constants.DEFAULT_CRS
) -> gpd.GeoDataFrame:
    """Load a single territorial authority by name.

    Args:
        name: The authority's name, e.g. "Wellington City". Matched case
            insensitively.
        crs: The coordinate reference system to return the boundary in.

    Returns:
        A GeoDataFrame with the one matching row.

    Raises:
        KeyError: If no authority of that name is in the study area.
    """
    study_areas = get_study_areas(crs)
    match = study_areas.loc[study_areas["name"].str.lower() == name.lower()]

    if match.empty:
        known = ", ".join(sorted(study_areas["name"]))
        msg = f"{name!r} is not in the study area. Available: {known}"
        raise KeyError(msg)

    return match.reset_index(drop=True)


def study_area_bbox(
    crs: int | str = constants.DEFAULT_CRS,
) -> tuple[float, float, float, float]:
    """Return the bounding box covering all four territorial authorities.

    Args:
        crs: The coordinate reference system to express the extent in.

    Returns:
        The bounding box (minx, miny, maxx, maxy), ready to pass to a reader.
    """
    minx, miny, maxx, maxy = get_study_areas(crs).total_bounds
    return (float(minx), float(miny), float(maxx), float(maxy))
